version: '3.8'

services:
  # Core API service
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - ./data:/app/data
    environment:
      - LLM_PROVIDER=ollama
      - LLM_MODEL=llama3  # Changed to use llama3 as mentioned
      - LLM_API_BASE=http://192.168.5.199:11434/api  # Using host's actual IP
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    depends_on:
      - vector-db
    command: ["python", "-m", "src.main", "--mode", "api", "--config", "configs/config.yaml"]
    networks:
      - infra-network
    restart: unless-stopped

  # Vector database for agent memory
  vector-db:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./vector-db-data:/qdrant/storage
    networks:
      - infra-network
    restart: unless-stopped

networks:
  infra-network:
    driver: bridge
