version: '3.8'

services:
  # Core API service
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - chroma_data:/app/chroma_data
    environment:
      - LLM_PROVIDER=ollama
      - LLM_MODEL=llama3
      - LLM_API_BASE=http://172.17.0.1:11434
      - CHROMA_DB_PATH=/app/chroma_data
      - PYTHONPATH=/app
    networks:
      - infra_network
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Test service for running automated tests
  test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./test-results:/app/test-results
    environment:
      - LLM_PROVIDER=ollama
      - LLM_MODEL=llama3
      - LLM_API_BASE=http://172.17.0.1:11434
      - TESTING=1
      - PYTHONPATH=/app
    networks:
      - infra_network
    command: python -m src.tests.run_tests
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  infra_network:
    driver: bridge

volumes:
  chroma_data: